maityamit/Tracky-Track-your-goals-or-targets

app/src/main/java/achivementtrackerbyamit/example/achivetracker/MainActivity.java
@maityamit 
Please review my PR.
#issue3 : Adding alert dialog for confirmation of logout
=> Adding alert dialog for confirmation of logout

.idea/gradle.xml, app/src/main/java/achivementtrackerbyamit/example/achivetracker/MainActivity.java
The remaining days remained "days", when 1 day was left. It is updated to "day", whenever a single day is left.
=> consistency display updated

.idea/gradle.xml, .idea/misc.xml, app/build.gradle, app/src/main/java/achivementtrackerbyamit/example/achivetracker/AddtripActivity.java, app/src/main/res/drawable/ic_baseline_arrow_drop_down_24.xml, app/src/main/res/drawable/ic_wave__9.xml, app/src/main/res/layout/activity_addtrip.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/themes.xml
Make the new design of adTripActivity as instructed.
=> a new xml added for addTripActivity

app/src/main/java/achivementtrackerbyamit/example/achivetracker/ActiveGoalFragment.java, app/src/main/java/achivementtrackerbyamit/example/achivetracker/HomeActivity.java, app/src/main/java/achivementtrackerbyamit/example/achivetracker/ProfileActivity.java, app/src/main/java/achivementtrackerbyamit/example/achivetracker/SignupActivity.java, app/src/main/res/drawable/material_dialog_box.xml, app/src/main/res/layout/activity_signin.xml, app/src/main/res/values/style.xml
=> 5 minor issues done

.idea/gradle.xml, app/src/main/java/achivementtrackerbyamit/example/achivetracker/SignupActivity.java, app/src/main/res/layout/activity_signup.xml
=> Image Upload option implemented on Signup Activity

app/src/main/java/achivementtrackerbyamit/example/achivetracker/DashboardActivity.java
Text with image added in sharing feature
e
=> Text in sharing added

.idea/deploymentTargetDropDown.xml, .idea/gradle.xml, app/src/main/java/achivementtrackerbyamit/example/achivetracker/AddtripActivity.java, app/src/main/java/achivementtrackerbyamit/example/achivetracker/DashboardActivity.java, app/src/main/res/drawable/ic_baseline_edit_24.xml, app/src/main/res/layout/activity_addtrip.xml, app/src/main/res/layout/activity_dashboard.xml, app/src/main/res/values/strings.xml
@maityamit  Please review it and let me know, if there are something wrong.
closes #40
=> Dash Board Activity : Edit Goal Name and Goal Target date change option make

.idea/compiler.xml, .idea/gradle.xml, .idea/misc.xml, app/src/main/java/achivementtrackerbyamit/example/achivetracker/ProfileActivity.java, app/src/main/res/layout/activity_profile.xml
Added feature to update username from Firebase
=> Added Username Update Feature

.idea/gradle.xml, .idea/misc.xml, app/src/main/java/achivementtrackerbyamit/example/achivetracker/DashboardActivity.java, app/src/main/res/layout/activity_dashboard.xml
=> Delete goal option added

.idea/misc.xml, app/build.gradle, app/src/main/java/achivementtrackerbyamit/example/achivetracker/DashboardActivity.java, app/src/main/res/drawable-v24/calendar_background.xml, app/src/main/res/layout/activity_dashboard.xml
@maityamit Please review it and let me know whether it works correctly or not.
Closes #62
=> Highlights multiple date using MCalendarView

.idea/gradle.xml, .idea/misc.xml, app/src/main/java/achivementtrackerbyamit/example/achivetracker/HomeActivity.java, app/src/main/res/drawable/add.xml, app/src/main/res/layout/activity_home.xml
Added new drawable inplace of Floating Action button text.
Added Toast to inform the user about the button feature.
Screenshot:
=> Changed Action Button Style + UX

.idea/misc.xml, app/src/main/java/achivementtrackerbyamit/example/achivetracker/AddGoalActivity.java, app/src/main/java/achivementtrackerbyamit/example/achivetracker/DashboardActivity.java, app/src/main/res/drawable/ic_info.xml, app/src/main/res/layout/activity_addgoal.xml, app/src/main/res/layout/activity_dashboard.xml
=> Goal description added

.idea/gradle.xml, app/build.gradle, app/src/main/java/achivementtrackerbyamit/example/achivetracker/ProfileActivity.java, app/src/main/res/layout/activity_profile.xml
Added PDF creation feature with Dialog EditText Feature
=> Added PDF Feature

app/src/main/java/achivementtrackerbyamit/example/achivetracker/AddGoalActivity.java
User can't create Duplicate name Goals
=> Added Duplicate Name restriction Feature

app/src/main/java/achivementtrackerbyamit/example/achivetracker/ActiveGoalFragment.java, app/src/main/java/achivementtrackerbyamit/example/achivetracker/HomeActivity.java, app/src/main/res/layout/activity_home.xml, app/src/main/res/layout/fragment_active_goal.xml
=> Removed Floating Action Button from other fragments

.idea/gradle.xml, .idea/misc.xml, app/src/main/java/achivementtrackerbyamit/example/achivetracker/DashboardActivity.java, app/src/main/res/layout/activity_dashboard.xml
=> Goal pic upload feature added

app/src/main/java/achivementtrackerbyamit/example/achivetracker/ActiveGoalFragment.java, app/src/main/java/achivementtrackerbyamit/example/achivetracker/AddGoalActivity.java
closes #89 
@maityamit  Please review it, and let me know, whether there is any problem or not.
=> Store and retrieve user activity from firebase

app/src/main/java/achivementtrackerbyamit/example/achivetracker/DashboardActivity.java, app/src/main/java/achivementtrackerbyamit/example/achivetracker/GoalAdapter.java, app/src/main/res/layout/main_tiles_layout.xml
=> Completed percentage Progress Bar on Active Goals

.idea/misc.xml, app/src/main/java/achivementtrackerbyamit/example/achivetracker/DashboardActivity.java, app/src/main/res/layout/activity_dashboard.xml
Added Share features in All Cards
=> Add Share Features

.idea/gradle.xml, .idea/misc.xml, app/src/main/java/achivementtrackerbyamit/example/achivetracker/GoalAdapter.java, app/src/main/res/layout/main_tiles_layout.xml
=> Retrieve Goal Image into CurrentGoal Frag Recyclerview items Done

app/src/main/java/achivementtrackerbyamit/example/achivetracker/AddGoalActivity.java, app/src/main/java/achivementtrackerbyamit/example/achivetracker/DashboardActivity.java, app/src/main/java/achivementtrackerbyamit/example/achivetracker/GoalAdapter.java, app/src/main/res/layout/activity_dashboard.xml
-Added a feature to ask for Break
=> Added On Break Feature

app/src/main/java/achivementtrackerbyamit/example/achivetracker/GoalAdapter.java, app/src/main/java/achivementtrackerbyamit/example/achivetracker/archive/ArchiveAdapter.java, app/src/main/res/layout/archive_goals_item_layout.xml
=> Consistency Percentage Progress Bar on Archived Goals

app/src/main/java/achivementtrackerbyamit/example/achivetracker/AddGoalActivity.java, app/src/main/java/achivementtrackerbyamit/example/achivetracker/DashboardActivity.java
Fixed Edit Goal issue, Now user can edit the goal without changing their name.
=> Fixed Edit issue

.idea/gradle.xml, .idea/misc.xml, app/src/main/java/achivementtrackerbyamit/example/achivetracker/AddGoalActivity.java, app/src/main/java/achivementtrackerbyamit/example/achivetracker/DashboardActivity.java, app/src/main/java/achivementtrackerbyamit/example/achivetracker/HomeActivity.java, app/src/main/res/drawable/addnew.xml, app/src/main/res/layout/activity_dashboard.xml
Added Daily Notes Adding Feature
=> NewNoteCreation

.idea/misc.xml, app/src/main/java/achivementtrackerbyamit/example/achivetracker/SettingsFragment.java, app/src/main/res/layout/show_log_dialog.xml
=> Show log dialog box

.idea/gradle.xml, .idea/misc.xml, app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/achivementtrackerbyamit/example/achivetracker/AddGoalActivity.java, app/src/main/java/achivementtrackerbyamit/example/achivetracker/GraphConsistency.java, app/src/main/java/achivementtrackerbyamit/example/achivetracker/ProfileActivity.java, app/src/main/java/achivementtrackerbyamit/example/achivetracker/active/ActiveGoalFragment.java, app/src/main/java/achivementtrackerbyamit/example/achivetracker/active/GoalAdapter.java, app/src/main/res/layout/activity_graph_consistency.xml, app/src/main/res/layout/activity_profile.xml
=> Added Graph Preview

.idea/gradle.xml, .idea/misc.xml, app/src/main/java/achivementtrackerbyamit/example/achivetracker/archive_goal/ArchiveAdapter.java, app/src/main/java/achivementtrackerbyamit/example/achivetracker/archive_goal/ArchiveGoalFragment.java, app/src/main/res/layout/archive_goals_item_layout.xml
closes #118 
@maityamit Please check again and let me know if there are something wrong.
=> Delete archive goal automatically after a particular time

app/src/main/java/achivementtrackerbyamit/example/achivetracker/HomeActivity.java, app/src/main/java/achivementtrackerbyamit/example/achivetracker/active_goal/ActiveGoalFragment.java, app/src/main/java/achivementtrackerbyamit/example/achivetracker/rank/RankAdapter.java, app/src/main/java/achivementtrackerbyamit/example/achivetracker/rank/RankFragment.java
=> Showing "Me" instead of username on rank list

app/src/main/java/achivementtrackerbyamit/example/achivetracker/ProfileActivity.java
=> Profile Image update issue fixed

.idea/gradle.xml, .idea/misc.xml, app/src/main/java/achivementtrackerbyamit/example/achivetracker/DashboardActivity.java, app/src/main/java/achivementtrackerbyamit/example/achivetracker/Notes.java, app/src/main/res/layout/activity_dashboard.xml, app/src/main/res/layout/notelist.xml
=> Streak Notes Done

app/src/main/java/achivementtrackerbyamit/example/achivetracker/ProfileActivity.java, app/src/main/java/achivementtrackerbyamit/example/achivetracker/SettingsFragment.java
=> Material Dialog Box for Logout

.idea/misc.xml, app/src/main/res/layout/activity_addgoal.xml
=> UI changed in Add Goal Activity

.idea/compiler.xml, .idea/gradle.xml, .idea/misc.xml, app/src/main/java/achivementtrackerbyamit/example/achivetracker/auth/ForgetpassActivity.java
=> Bug Fixed for Forgot Password

app/build.gradle, app/src/main/java/achivementtrackerbyamit/example/achivetracker/SettingsFragment.java
=> Rate Feature Done in Settings Fragment

.idea/misc.xml, app/src/main/java/achivementtrackerbyamit/example/achivetracker/DashboardActivity.java, app/src/main/res/layout/reset_dialog.xml
=> Fixed Undone Task

app/src/main/java/achivementtrackerbyamit/example/achivetracker/SettingsFragment.java
=> Dialog Box Added In Settings Fragment

app/src/main/java/achivementtrackerbyamit/example/achivetracker/DashboardActivity.java
=> Progress Dialog Box Fixed

.idea/misc.xml, app/src/main/java/achivementtrackerbyamit/example/achivetracker/AddGoalActivity.java, app/src/main/java/achivementtrackerbyamit/example/achivetracker/DashboardActivity.java, app/src/main/res/layout/activity_dashboard.xml
=> Add Graph in Dashboard

.idea/misc.xml, app/src/main/java/achivementtrackerbyamit/example/achivetracker/DashboardActivity.java
=> Reset button confirmation dialogue box

.idea/misc.xml, app/src/main/java/achivementtrackerbyamit/example/achivetracker/active_goal/ActiveGoalFragment.java, app/src/main/res/layout/fragment_active_goal.xml
=> Added Goal Counter

.idea/misc.xml, app/src/main/java/achivementtrackerbyamit/example/achivetracker/AddGoalActivity.java
=> Goal Description Retrieved

.idea/compiler.xml, .idea/gradle.xml, .idea/misc.xml, app/src/main/res/layout/activity_splassh.xml
=> Logo changed in Splash Screen

.idea/misc.xml, app/src/main/java/achivementtrackerbyamit/example/achivetracker/SettingsFragment.java, app/src/main/java/achivementtrackerbyamit/example/achivetracker/active_goal/GoalAdapter.java, app/src/main/res/drawable/feedbk.xml, app/src/main/res/drawable/gr.xml, app/src/main/res/drawable/rd.xml, app/src/main/res/drawable/yl.xml, app/src/main/res/layout/fragment_settings.xml, app/src/main/res/layout/main_tiles_layout.xml
=> Added Feedback and Card Changes

app/src/main/java/achivementtrackerbyamit/example/achivetracker/splash/SplasshActivity.java
=> Fixed Splash Screen

app/src/main/java/achivementtrackerbyamit/example/achivetracker/ProfileActivity.java
=> Fixed Issue No 257

app/src/main/java/achivementtrackerbyamit/example/achivetracker/active_goal/GoalAdapter.java, app/src/main/java/achivementtrackerbyamit/example/achivetracker/archive_goal/ArchiveAdapter.java, app/src/main/java/achivementtrackerbyamit/example/achivetracker/archive_goal/ArchiveClass.java, app/src/main/java/achivementtrackerbyamit/example/achivetracker/archive_goal/ArchiveGoalFragment.java
=> Auto delete archive goal

.idea/misc.xml, app/src/main/java/achivementtrackerbyamit/example/achivetracker/rank/RankAdapter.java, app/src/main/java/achivementtrackerbyamit/example/achivetracker/rank/RankFragment.java, app/src/main/res/layout/user_display.xml, app/src/main/res/values/strings.xml
=> Added Card Dialog to show User details in Leaderboard

.idea/misc.xml, app/src/main/res/font/alice.xml, app/src/main/res/font/balthazar.xml, app/src/main/res/layout/activity_home.xml, app/src/main/res/layout/fragment_active_goal.xml, app/src/main/res/values/preloaded_fonts.xml
=> Search bar UI changed

app/src/main/java/achivementtrackerbyamit/example/achivetracker/active_goal/ActiveGoalFragment.java
=> Search bug fixed
